services:
  jekyll:
    image: jekyll/jekyll:4
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - ./_site:/srv/jekyll/_site
    command: jekyll serve --host 0.0.0.0 --port 4000 --livereload --force_polling
